"""Narrow Hermes integration. Cron owns scheduling and transport."""
from __future__ import annotations

import json
import os
import tempfile
import time
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

from .service import Companion, DEFAULT_PREFERENCES
from .store import PLUGIN, VERSION, Store, epoch, stamp

JOBS = {"proactive-watch": "*/30 * * * *", "memory-upkeep": "0 * * * *",
        "nightly-review": "20 3 * * *", "feed-pulse": "0 * * * *"}
ROOT = Path(__file__).resolve().parent.parent


@contextmanager
def profile_scope(home):
    from hermes_constants import set_hermes_home_override, reset_hermes_home_override
    token = set_hermes_home_override(home)
    try:
        yield
    finally:
        reset_hermes_home_override(token)


@contextmanager
def file_lock(path):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise ValueError("Lock file must not be a symlink")
    with path.open("a+b") as handle:
        if os.name == "nt":
            import msvcrt
            if handle.tell() == 0:
                handle.write(b"0")
                handle.flush()
            handle.seek(0)
            msvcrt.locking(handle.fileno(), msvcrt.LK_LOCK, 1)
        else:
            import fcntl
            fcntl.flock(handle, fcntl.LOCK_EX)
        try:
            yield
        finally:
            if os.name == "nt":
                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
            else:
                fcntl.flock(handle, fcntl.LOCK_UN)


class HermesHost:
    def __init__(self, store, plugin_root=ROOT):
        self.store, self.home, self.root = store, store.home, Path(plugin_root).resolve()

    def manifest(self):
        path = self.store.path("install.json")
        if not path.exists():
            return {"plugin": PLUGIN, "version": VERSION, "installation_id": uuid.uuid4().hex,
                    "jobs": {}, "fixed": {}, "scripts": []}
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("plugin") != PLUGIN:
            raise ValueError("An unrelated installation record occupies muse/install.json")
        return data

    def save_manifest(self, manifest):
        manifest["version"] = VERSION
        self.store.write_text("install.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")

    def _launcher(self, key, record):
        relative = f"scripts/hermes-muse-{key}.py"
        path = self.home / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink() or not path.resolve().is_relative_to(self.home):
            raise ValueError("Cron launcher escapes the active profile")
        content = (
            "# Generated by hermes-muse; owned entrypoint, not user code.\n"
            "import json\nfrom pathlib import Path\nimport runpy\n"
            f"entry = Path({str(self.root / 'cron_entry.py')!r})\n"
            "if not entry.is_file():\n    print(json.dumps({'wakeAgent': False}))\n"
            "else:\n    runpy.run_path(str(entry), init_globals={"
            f"'MUSE_HOME': str(Path(__file__).resolve().parent.parent), 'MUSE_JOB': {key!r}"
            "}, run_name='__main__')\n"
        )
        if path.exists() and relative not in record["scripts"] and not path.read_text(encoding="utf-8").startswith("# Generated by hermes-muse;"):
            raise ValueError(f"Refusing to overwrite an existing unrelated script: {path}")
        temporary = path.with_suffix(".tmp")
        if temporary.is_symlink():
            raise ValueError("Unsafe temporary launcher path")
        temporary.write_text(content, encoding="utf-8")
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
        if relative not in record["scripts"]:
            record["scripts"].append(relative)
        return path.name

    def _owned_job(self, key, options, *, owner=None, item=None, fixed=False, expires=None):
        from cron.jobs import create_job, get_job, list_jobs, update_job
        with profile_scope(self.home), file_lock(self.store.path("install.lock")):
            record = self.manifest()
            marker = f"[hermes-muse:{record['installation_id']}:{key}]"
            existing = None
            for job in list_jobs(include_disabled=True):
                if marker not in job.get("prompt", "") or job.get("workdir") != str(self.store.root):
                    continue
                if fixed or job.get("state") not in {"completed", "failed", "cancelled"} and job.get("next_run_at"):
                    existing = job
                    break
            script = self._launcher(key, record)
            prompt = marker + "\n" + options.pop("prompt", "")
            if existing:
                if fixed:
                    # Refresh shipped instructions while preserving user pause/schedule/model choices.
                    existing = update_job(existing["id"], {"prompt": prompt, "script": script, "skills": [f"{PLUGIN}:companion"]})
                job = existing
            else:
                job = create_job(prompt=prompt, script=script, workdir=str(self.store.root), **options)
            record["jobs"][job["id"]] = {"key": key, "owner": owner, "item": item, "marker": marker, "expires": expires}
            if fixed:
                record["fixed"][key] = job["id"]
            self.save_manifest(record)
            return job

    def initialize(self):
        from cron.jobs import create_job
        from hermes_cli.plugins import PluginContext
        if not callable(getattr(PluginContext, "register_system_prompt_section", None)):
            raise RuntimeError("Hermes lacks register_system_prompt_section; update Hermes")
        with file_lock(self.store.path("install.lock")):
            record = self.manifest()
            self.save_manifest(record)  # identity is durable before any external job creation
            for file in (self.root / "templates").rglob("*.md"):
                relative = file.relative_to(self.root / "templates").as_posix()
                content = file.read_text(encoding="utf-8").replace("{{MUSE_HOME}}", str(self.store.root)).replace("{{HERMES_HOME}}", str(self.home))
                self.store.write_text(relative, content, create_only=True)
            for folder in ("memory/people", "memory/groups", "dreams/alignment/derived", "workspace/goals", "workspace/your_files/feed"):
                self.store.path(folder).mkdir(parents=True, exist_ok=True)
        for key, schedule in JOBS.items():
            prompt = (self.root / "prompts" / f"{key}.md").read_text(encoding="utf-8")
            self._owned_job(key, {"name": "muse-" + key, "schedule": schedule,
                                  "prompt": prompt, "skills": [f"{PLUGIN}:companion"], "deliver": "local",
                                  "attach_to_session": False}, fixed=True)
        return self.manifest()

    def wake(self, key):
        from cron.jobs import get_job, update_job
        with profile_scope(self.home):
            job_id = self.manifest()["fixed"].get(key)
            job = get_job(job_id) if job_id else None
            if job and job.get("enabled"):
                update_job(job_id, {"next_run_at": stamp(time.time() + 1)})
                return True
        return False

    def route(self, session_id=None):
        if session_id:
            session = self.store.read("session", session_id, {})
            route = session.get("route")
            if route and route.get("platform") and route.get("chat_id"):
                return route
        from cron.scheduler_delivery import cron_delivery_targets
        with profile_scope(self.home):
            targets = cron_delivery_targets()
        # No fan-out and no arbitrary choice when more than one home destination exists.
        homes = [r for r in targets if r.get("home_target_set") and not r["id"].startswith("bot:")]
        if len(homes) == 1:
            return {"deliver": homes[0]["id"]}
        return None

    def delivery_job(self, notification, route):
        return self._owned_job("deliver-" + notification["id"], {
            "name": "muse-delivery-" + notification["id"], "schedule": stamp(time.time() + 60),
            "prompt": "Deliver the plugin's revalidated prepared notice; the script owns the output.",
            "no_agent": True, "deliver": route.get("deliver", "origin"),
            "origin": route if route.get("chat_id") else None, "attach_to_session": True,
        }, owner=notification.get("goal_id"), item=notification["id"])

    def watch(self, data):
        goal, _ = self.store.goal(data["goal_id"])
        if goal["status"] != "active":
            raise ValueError("A watch requires an active goal")
        with self.store.transaction() as db:
            Companion(self.store, self).require_signal(db, data.get("signal_id"))
        expires = epoch(data["expires"]) if data.get("expires") else None
        if expires is not None and expires <= time.time():
            raise ValueError("Watch expiry must be in the future")
        key = "watch-" + uuid.uuid4().hex[:12]
        prompt = ("Read hermes-muse:companion and muse_manage context. Work only on goal " + goal["id"] + ". "
                  "Check its status and your stop condition first. Never send directly; prepare evidence with notification_add and notification_queue. "
                  "Stop and call watch_stop when the promised condition is satisfied. Return [SILENT].\n"
                  + str(data["prompt"]) + "\nStop condition: " + str(data["stop_condition"]))
        return self._owned_job(key, {"name": "muse-" + key, "schedule": data["schedule"], "prompt": prompt,
                                   "skills": [f"{PLUGIN}:companion"], "deliver": "local"}, owner=goal["id"], expires=expires)

    def pause_owner(self, owner):
        from cron.jobs import pause_job, get_job
        with profile_scope(self.home):
            for job_id, record in self.manifest()["jobs"].items():
                if record.get("owner") != owner:
                    continue
                if record.get("item"):
                    row = self.store.read("notification", record["item"], {})
                    if row.get("final_result"):
                        continue
                if get_job(job_id):
                    pause_job(job_id, reason="Hermes Muse: owning goal closed")

    def stop_watch(self, job_id):
        from cron.jobs import pause_job
        owned = self.manifest()["jobs"].get(job_id)
        if not owned or not owned["key"].startswith("watch-"):
            raise ValueError("Not a plugin-owned watch")
        with profile_scope(self.home):
            return pause_job(job_id, reason="Hermes Muse: watch completed or cancelled")

    def reconcile(self):
        from cron.executions import latest_execution
        updates = []
        for row in self.store.all("notification"):
            if row["status"] not in {"dispatching", "queued", "transport_queued"} or not row.get("job_id"):
                continue
            with profile_scope(self.home):
                execution = latest_execution(row["job_id"])
            if not execution or execution["status"] in {"claimed", "running"}:
                continue
            outcome = execution.get("delivery_outcome")
            if row["status"] == "queued":
                # The script was never entered: preparation failed, no receipt is implied.
                status = "failed" if execution["status"] == "failed" else "unknown"
            elif execution["status"] == "completed" and outcome == "delivered":
                status = "sent"
            elif outcome == "queued":
                from cron.delivery_queue import get_status
                with profile_scope(self.home):
                    receipt = get_status(execution["id"])
                queue_status = (receipt or {}).get("status")
                status = "sent" if queue_status == "delivered" else "unknown" if queue_status in {"failed", "unknown", "suppressed"} else "transport_queued"
            else:
                status = "unknown"  # including partial sends/timeouts: never blindly replay
            row.update(status=status, execution_id=execution["id"], delivery_outcome=outcome,
                       delivery_note="Native transport report; not a phone display/read receipt.")
            with self.store.transaction() as db:
                current = self.store.get(db, "notification", row["id"])
                if current and current["status"] in {"dispatching", "queued", "transport_queued"}:
                    self.store.put(db, "notification", row["id"], row)
            updates.append(row)
        return updates

    def local_now(self, timestamp):
        from hermes_time import now
        with profile_scope(self.home):
            return datetime.fromtimestamp(timestamp, now().tzinfo)


def enabled(home):
    """Read host consent; removal/disable must make remaining launchers harmless."""
    from hermes_cli.config import load_config
    with profile_scope(home):
        cfg = load_config()
    plugins = cfg.get("plugins", {})
    return PLUGIN in plugins.get("enabled", []) and PLUGIN not in plugins.get("disabled", [])


def cron_run(home, key):
    if not enabled(home):
        return {"wakeAgent": False, "reason": "plugin absent or disabled"}
    store = Store(home)
    host = HermesHost(store)
    service = Companion(store, host)
    host.reconcile()
    if key.startswith("deliver-"):
        return service.delivery_text(key[len("deliver-"):])
    context = service.context()
    if key.startswith("watch-"):
        pair = next(((jid, r) for jid, r in host.manifest()["jobs"].items() if r["key"] == key), None)
        owned = pair[1] if pair else None
        if not owned:
            return {"wakeAgent": False}
        if owned.get("expires") is not None and owned["expires"] <= time.time():
            host.stop_watch(pair[0])
            return {"wakeAgent": False, "reason": "watch expired"}
        try:
            goal, _ = store.goal(owned["owner"])
            return {"wakeAgent": goal["status"] == "active", "goal": goal["id"]}
        except ValueError:
            return {"wakeAgent": False}
    now = time.time()
    signals = context["new_user_signals"]
    if key == "memory-upkeep":
        wake = bool(signals)
    elif key == "feed-pulse":
        wake = bool(context["interests_and_ideas"] or context["goals"] or context["preferences"]["feed_brief"])
    elif key == "nightly-review":
        nightly_cursor = store.read("cursor", "nightly-review", 0)
        fresh = any(s["created"] > nightly_cursor for s in store.all("signal"))
        wake = bool(fresh or context["goals"] or context["goals_needing_review"] or context["interests_and_ideas"])
    else:
        # Retry only deferred selection, never unknown/dispatching sends.
        for row in context["notifications"]:
            if row["status"] == "pending" and row["not_before"] <= now and row["expires"] > now:
                service.notification_queue({"id": row["id"]})
        wake = bool(context["goals"] or context["interests_and_ideas"] or any(r["status"] == "candidate" for r in context["notifications"]))
    return {"wakeAgent": wake, "job": key, "started_at": stamp(now),
            "instruction": "Call muse_manage context for current facts, then follow this job's Skill procedure. Advance review_complete only after successful writes."}
